<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{A Markdown Vignette with knitr}
-->

```{r setup, include=FALSE}
library(knitr)
options(width=120)
opts_chunk$set(fig.path="figure/", cache.path="cache/", fig.align="center", warning=FALSE, message=FALSE, fig.height=7, fig.width=5)
```

Introduction to XML2R package
====================================

Extracting entire documents
--------------------------

The  **XML2R** package is meant to simplify scraping XML data from the web. All you need is a collection of urls that point to XML files. By default, `XML2R` will pool all information into a list of matrices -- each corresponding to a common XML node. Here is a simple example:

```{r ex1, tidy=FALSE, results='hide'}
library(XML2R)
urls <- c("http://gd2.mlb.com/components/game/mlb/year_2013/mobile/346180.xml", 
          "http://gd2.mlb.com/components/game/mlb/year_2013/mobile/346188.xml")
dat <- XML2R(urls)
```

```{r ex1a}
names(dat)
```

Within these two files (which have similar and fairly simple structure), there are nine different "levels" of information. For example, the first element of `dat` corresponds to all information occuring on the "`r names(dat)[1]` level". Lets take a look at the first 10 occurences of this XML node:

```{r ex1b}
head(dat[[1]], 10)
```

This XML node has five different attributes: "id", "date", "type", "top-play" and "condensed". The condensed attribute is missing in most cases, but in the eighth row "condensed" appears while "top-play" is now missing. For tracking purposes, `XML2R` will also append a column names `URL_source` which can be used to track observations back to their file. Since some urls can be quite long, we store the mapping from values in this column to the actual file name via the `dat[["url_map"]]`

```{r ex1c}
dat[["url_map"]]
```

Another nice aspect of `XML2R` is the automatic inclusion of both XML values and attributes. For example, information on the `r names(dat)[5]` level contains both values and attributes. In this case, there is one unique attribute -- "player_id". 

```{r ex1d}
dat[[5]]
```

Using XPath
--------------------------

If one is interested in just a subset of the XML document, the `xpath` option of `XML2R` can be used to specify [XPath syntax](http://www.w3schools.com/xpath/xpath_syntax.asp). Suppose I'm just interested in information that occurs on the `highlights//media//player` level. 

```{r xpath, results='hide'}
dat2 <- XML2R(urls, xpath="/highlights/media/player")
```

```{r xpath1}
dat2
```
